apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      env: test-1
  template:
    metadata:
      labels:
        env: test-1
    spec:
      initContainers:
        - name: first-container
          image: first
        - name: second-container
          image: second
      containers:
        - name: main-container
          image: busybox
          command: ['sh', '-c', 'echo "Succesfully ran both containers in order!"']
